import "./globals.css";
import { Analytics } from "@vercel/analytics/next"
import SmoothScroll from "@/components/SmoothScroll";

export const metadata = {
  title: "Reddit Profile Roaster",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
